### ISSUE TITLE
req.params Cannot Be Sanitized by Application-Level Middleware

### ISSUE THREAD

**Issue by VoxBorealis** [AhmedAdelFahim/express-xss-sanitizer#18]
**Issue Details**

The readme claims this can sanitize `req.params` when used as a application-level middleware. However, this doesn’t seem possible given how Express processes route parameters.

In Express, `req.params` is populated only after the route has been matched, which occurs at the route level. Because `req.params` isn’t populated when application-level middleware executes, it’s inaccessible for sanitization at that stage. As a result, this (or any other middleware used at the application-level) cannot sanitize `req.params` if applied before routes are defined.

For example, with the following setup:
```
const express = require('express');
const bodyParser = require('body-parser');
const { xss } = require('express-xss-sanitizer');

const app = express();
app.use(bodyParser.json({ limit: '1kb' }));
app.use(bodyParser.urlencoded({ extended: true, limit: '1kb' }));
app.use(xss());

// Your routes
```
In this configuration, xss() cannot sanitize `req.params` because it runs before the parameters are available. Route-level middleware is necessary for any processing of `req.params` to ensure they’re populated first.

**Questions/Clarifications**

- Has this functionality not been tested with `req.params`, or is the middleware intended to be used only for `req.body` and `req.query`?
- If sanitizing `req.params` is indeed a goal for this middleware, documentation or examples clarifying how this should be done at the route level would be very helpful.

Thank you!

**Note**: For anyone considering upgrading to Express 5, please be aware that this (or similar) dependencies are incompatible, as `req.query` is immutable in Express 5.

**Comment by AhmedAdelFahim** [comment]
Hi @VoxBorealis,

Thank you for bringing this to our attention and for your detailed observations. You are absolutely correct: when used as application-level middleware, xss() can only sanitize req.query, req.headers, and req.body. Sanitizing req.params is not possible at this level because req.params is populated only after the route has been matched, which occurs at the route level.

To sanitize req.params, the middleware must be applied at the route level, ensuring that req.params is already populated. I've updated the documentation to clarify this distinction and provide examples of how to handle req.params sanitization at the route level.

Example
```javascript
const express = require('express');
const bodyParser = require('body-parser');
const { xss } = require('express-xss-sanitizer');

const app = express();

app.use(bodyParser.json({limit:'1kb'}));
app.use(bodyParser.urlencoded({extended: true, limit:'1kb'}));
app.post("/params/:val", xss(), function (req, res) {
      // your code
});

```
### Regarding Your Note:
You are correct that Express 5 introduces immutability for req.query, which would impact this and similar middleware. We will explore updates or alternatives to ensure compatibility with Express 5 and will provide guidance in future releases.

Thank you again for your valuable input, and feel free to share further feedback or suggestions!

**Comment by AhmedAdelFahim** [comment]
@VoxBorealis express version 5 is supported in #21
